/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-09 08:57:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.qna;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class qnaList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1583484842632L));
    _jspx_dependants.put("jar:file:/C:/git/plzSeatdown/plzSeatdown/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/boardcss.css\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/nav.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Main -->\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("        <nav id=\"frequent\" class=\"py-5\">\r\n");
      out.write("            <ul id=\"frequentul\" class=\"d-flex justify-content-center\">\r\n");
      out.write("                <li><a href=\"#frequent\" class=\"active\">자주 묻는 질문</a></li>\r\n");
      out.write("                <li><a href=\"#faq\">고객 센터</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div>\r\n");
      out.write("            <h4 class=\"font-weight-bold\" style=\"color:#917EC6;\">자주 묻는 질문</h4>\r\n");
      out.write("            <h5 class=\"text-muted\">Frequently Asked Question</h5>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"accordion py-5\" id=\"accordionExample\">\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("                <div class=\"cheader account py-2 pr-1\" id=\"headingOne\" data-toggle=\"collapse\" data-target=\"#collapseOne\" aria-expanded=\"true\" aria-controls=\"collapseOne\">\r\n");
      out.write("                    <h2 class=\"mb-0 d-flex justify-content-between\">\r\n");
      out.write("                        <a class=\"btn btn-link collapsed\" type=\"button\">Q [계정관리] 이름을 수정하고 싶어요</a>\r\n");
      out.write("                        <i class=\"fas fa-angle-down\" style=\"color:white;\"></i>\r\n");
      out.write("                    </h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"collapseOne\" class=\"collapse\" aria-labelledby=\"headingOne\" data-parent=\"#accordionExample\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        이름 수정은 개명을 한 경우에만 수정이 가능하며\r\n");
      out.write("                        고객센터로 문의 시 변경가능합니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("                <div class=\"cheader account py-2 pr-1\" id=\"headingTwo\" data-toggle=\"collapse\"\r\n");
      out.write("                data-target=\"#collapseTwo\" aria-expanded=\"false\" aria-controls=\"collapseTwo\">\r\n");
      out.write("                    <h2 class=\"mb-0 d-flex justify-content-between\">\r\n");
      out.write("                        <a class=\"btn btn-link collapsed\" type=\"button\" >\r\n");
      out.write("                            Q [계정관리] 이메일 수정은 어떻게 하나요?\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <i class=\"fas fa-angle-down\" style=\"color:white;\"></i>\r\n");
      out.write("                    </h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"collapseTwo\" class=\"collapse\" aria-labelledby=\"headingTwo\" data-parent=\"#accordionExample\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        고객 센터로 문의 바랍니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("                <div class=\"cheader inform py-2 pr-1\" id=\"headingThree\" data-toggle=\"collapse\"\r\n");
      out.write("                data-target=\"#collapseThree\" aria-expanded=\"false\" aria-controls=\"collapseThree\">\r\n");
      out.write("                    <h2 class=\"mb-0 d-flex justify-content-between\">\r\n");
      out.write("                        <a class=\"btn btn-link collapsed\" type=\"button\" >\r\n");
      out.write("                            Q [공연정보] 공연장이 없어요\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <i class=\"fas fa-angle-down\" style=\"color:white;\"></i>\r\n");
      out.write("                    </h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"collapseThree\" class=\"collapse\" aria-labelledby=\"headingThree\" data-parent=\"#accordionExample\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        현재 일부 공연장만 서비스 중에 있으며 그 외 공연장을 점차 추가 제공할 예정입니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("                <div class=\"cheader inform py-2 pr-1\" id=\"headingFour\" data-toggle=\"collapse\"\r\n");
      out.write("                data-target=\"#collapseFour\" aria-expanded=\"false\" aria-controls=\"collapseFour\">\r\n");
      out.write("                    <h2 class=\"mb-0 d-flex justify-content-between\">\r\n");
      out.write("                        <a class=\"btn btn-link collapsed\" type=\"button\" >\r\n");
      out.write("                            Q [공연정보] 공연 정보가 잘못되었어요.\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <i class=\"fas fa-angle-down\" style=\"color:white;\"></i>\r\n");
      out.write("                    </h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"collapseFour\" class=\"collapse\" aria-labelledby=\"headingFour\" data-parent=\"#accordionExample\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        저희 사이트는 KOPIS 공연예술 통합전산망 www.kopis.or.kr 데이터를 이용하고 있으며\r\n");
      out.write("                        잘못된 정보는 고객센터로 문의하면 확인 후 수정하겠습니다.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("                <div class=\"cheader review py-2 pr-1\" id=\"headingFive\" data-toggle=\"collapse\"\r\n");
      out.write("                data-target=\"#collapseFive\" aria-expanded=\"false\" aria-controls=\"collapseFive\">\r\n");
      out.write("                    <h2 class=\"mb-0 d-flex justify-content-between\">\r\n");
      out.write("                        <a class=\"btn btn-link collapsed\" type=\"button\">\r\n");
      out.write("                            Q [좌석리뷰] 공연장과 실제 좌석 배치가 달라요\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <i class=\"fas fa-angle-down\" style=\"color:white;\"></i>\r\n");
      out.write("                    </h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"collapseFive\" class=\"collapse\" aria-labelledby=\"headingFive\" data-parent=\"#accordionExample\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.\r\n");
      out.write("                        3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt\r\n");
      out.write("                        laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin\r\n");
      out.write("                        coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes\r\n");
      out.write("                        anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings\r\n");
      out.write("                        occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard\r\n");
      out.write("                        of them accusamus labore sustainable VHS.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("                <div class=\"cheader review py-2 pr-1\" id=\"headingSix\" data-toggle=\"collapse\"\r\n");
      out.write("                data-target=\"#collapseSix\" aria-expanded=\"false\" aria-controls=\"collapseSix\">\r\n");
      out.write("                    <h2 class=\"mb-0 d-flex justify-content-between\">\r\n");
      out.write("                        <a class=\"btn btn-link collapsed\" type=\"button\">\r\n");
      out.write("                            Q [좌석리뷰] 공연과 상관없는 이미지로 리뷰를 올린 경우\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <i class=\"fas fa-angle-down\" style=\"color:white;\"></i>\r\n");
      out.write("                    </h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"collapseSix\" class=\"collapse\" aria-labelledby=\"headingSix\" data-parent=\"#accordionExample\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.\r\n");
      out.write("                        3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt\r\n");
      out.write("                        laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin\r\n");
      out.write("                        coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes\r\n");
      out.write("                        anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings\r\n");
      out.write("                        occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard\r\n");
      out.write("                        of them accusamus labore sustainable VHS.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("                <div class=\"cheader commu py-2 pr-1\" id=\"headingSeven\" data-toggle=\"collapse\"\r\n");
      out.write("                data-target=\"#collapseSeven\" aria-expanded=\"false\" aria-controls=\"collapseSeven\">\r\n");
      out.write("                    <h2 class=\"mb-0 d-flex justify-content-between\">\r\n");
      out.write("                        <a class=\"btn btn-link collapsed\" type=\"button\">\r\n");
      out.write("                            Q [커뮤니티] 사이트 내 공연 티켓 양도 및 거래 \r\n");
      out.write("                        </a>\r\n");
      out.write("                        <i class=\"fas fa-angle-down\" style=\"color:white;\"></i>\r\n");
      out.write("                    </h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"collapseSeven\" class=\"collapse\" aria-labelledby=\"headingSeven\" data-parent=\"#accordionExample\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.\r\n");
      out.write("                        3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt\r\n");
      out.write("                        laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin\r\n");
      out.write("                        coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes\r\n");
      out.write("                        anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings\r\n");
      out.write("                        occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard\r\n");
      out.write("                        of them accusamus labore sustainable VHS.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"card mb-3\">\r\n");
      out.write("                <div class=\"cheader commu py-2 pr-1\" id=\"headingEight\" data-toggle=\"collapse\"\r\n");
      out.write("                data-target=\"#collapseEight\" aria-expanded=\"false\" aria-controls=\"collapseEight\">\r\n");
      out.write("                    <h2 class=\"mb-0 d-flex justify-content-between\">\r\n");
      out.write("                        <a class=\"btn btn-link collapsed\" type=\"button\">\r\n");
      out.write("                            Q [커뮤니티] 커뮤니티 게시판 내 분쟁 발생 시\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <i class=\"fas fa-angle-down\" style=\"color:white;\"></i>\r\n");
      out.write("                    </h2>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"collapseEight\" class=\"collapse\" aria-labelledby=\"headingEight\" data-parent=\"#accordionExample\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid.\r\n");
      out.write("                        3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt\r\n");
      out.write("                        laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin\r\n");
      out.write("                        coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes\r\n");
      out.write("                        anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings\r\n");
      out.write("                        occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard\r\n");
      out.write("                        of them accusamus labore sustainable VHS.\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <hr>\r\n");
      out.write("\r\n");
      out.write("        <!-- 고객 센터 -->\r\n");
      out.write("        <div id=\"faq\" class=\"py-5\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"pb-5\">\r\n");
      out.write("                <h4 class=\"font-weight-bold\" style=\"color:#917EC6;\">고객 센터</h4>\r\n");
      out.write("                <h5 class=\"text-muted\">Service Center</h5>\r\n");
      out.write("            </div>\r\n");
      out.write("            <form method=\"POST\" action=\"insert\" role=\"form\" onsubmit=\"return validate();\">\r\n");
      out.write("                <div>\r\n");
      out.write("                \t<input type=\"hidden\" name=\"writer\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                    <textarea class=\"form-control\" rows=\"5\" id=\"content\" name=\"qnaContent\" placeholder=\"문의 내용을 입력해주세요\"\r\n");
      out.write("                        style=\"resize: none\"></textarea>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"float-right pt-3 pb-5 mb-5\">\r\n");
      out.write("\t                ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// 유효성 검사\r\n");
      out.write("\t\tfunction validate(){\r\n");
      out.write("\t\t\tif($(\"#content\").val().trim().length == 0){\r\n");
      out.write("\t\t\t\talert(\"내용을 입력해 주세요.\");\r\n");
      out.write("\t\t\t\t$(\"#content\").focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/qna/qnaList.jsp(212,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty loginMember && loginMember.memberStatus == 'Y'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t                    <button type=\"submit\" class=\"btn btn-outline-secondary\">문의하기</button>\r\n");
          out.write("\t                ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
