/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-03-09 08:29:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class communityDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1583484842632L));
    _jspx_dependants.put("jar:file:/C:/git/plzSeatdown/plzSeatdown/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/boardcss.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/main.css\" />\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("<title>게시글 상세</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write('	');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/nav.jsp", out, false);
      out.write("\r\n");
      out.write("        <!-- Main -->\r\n");
      out.write("\t\t\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div>\r\n");
      out.write("            \t<!-- 가장 최신글은 이전글이 안뜸 -->\r\n");
      out.write("            \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                <button id=\"prev\" class=\"btn btn-sm btn-outline-secondary\">이전글</button>\r\n");
      out.write("                <!-- 가장 마지막글은 다음글이 안뜸 -->\r\n");
      out.write("                <button id=\"next\" class=\"btn btn-sm btn-outline-secondary\">다음글</button>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${header.referer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btn btn-sm btn-outline-secondary float-right\">목록</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div>\r\n");
      out.write("                <hr>\r\n");
      out.write("                <div class=\"pb-3\" style=\"border-bottom: 1px dashed rgba(0,0,0,.1);\">\r\n");
      out.write("                    <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comm.commTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                    <span class=\"text-muted\">[카테고리]</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"pt-3\">\r\n");
      out.write("                    <img class=\"rounded-circle\" style=\"width:20px; height:20;\"src=\"images/pic01.jpg\">\r\n");
      out.write("                    <p style=\"display: inline-block;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comm.commNickNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                    <p class=\"float-right text-muted\" style=\"display: inline-block;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comm.commModifyDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                    <p class=\"float-right text-muted mr-4\" style=\"display: inline-block;\">조회수 &nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comm.commCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"my-4 py-5\">\r\n");
      out.write("                    <p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comm.commContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <span>댓글</span>&nbsp;&nbsp;\r\n");
      out.write("                    <span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${comm.commReplyCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                    <a href=\"#\" class=\"float-right text-muted\">신고</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 댓글 -->\r\n");
      out.write("                <div class=\"my-3 pt-2 pb-5 px-4 \" style=\"background-color: #f7f7f9;\" id=\"reply-area \">\r\n");
      out.write("                    <!-- 댓글 출력 부분 -->\r\n");
      out.write("                    <div class=\"replyList\">\r\n");
      out.write("                        <ul class=\"comments-list\">\r\n");
      out.write("\r\n");
      out.write("                            <!-- 기본 댓글 출력 -->\r\n");
      out.write("                            <li class=\"comment\">\r\n");
      out.write("                                <a class=\"float-left\" href=\"#\">\r\n");
      out.write("                                    <img class=\"rounded-circle avatar\" src=\"http://bootdey.com/img/Content/user_1.jpg\" alt=\"avatar\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"comment-body\">\r\n");
      out.write("                                    <div class=\"comment-heading\">\r\n");
      out.write("                                        <h4 class=\"user\">Gavino Free</h4>\r\n");
      out.write("                                        <h5 class=\"time\">2020.02.24. 18:08</h5>\r\n");
      out.write("                                        <a href=\"#\" class=\"time pr-2 float-right\">신고</a>\r\n");
      out.write("                                        <a href=\"#\" class=\"time pr-2 float-right\">답글</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p>Sure, oooooooooooooooohhhhhhhhhhhhhhhh</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            \r\n");
      out.write("                            <!-- 답댓글 출력 -->\r\n");
      out.write("                            <li class=\"comment\">\r\n");
      out.write("                                <ul class=\"comments-list\">\r\n");
      out.write("                                    <li class=\"comment\">\r\n");
      out.write("                                        <a class=\"float-left\" href=\"#\">\r\n");
      out.write("                                            <i class=\"fa fa-reply fa-rotate-180 text-muted\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                            <img class=\"rounded-circle avatar\" src=\"http://bootdey.com/img/Content/user_3.jpg\" alt=\"avatar\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"comment-body\">\r\n");
      out.write("                                            <div class=\"comment-heading\">\r\n");
      out.write("                                                <h4 class=\"user\">Ryan Haywood</h4>\r\n");
      out.write("                                                <h5 class=\"time\">2020.02.24. 18:08</h5>\r\n");
      out.write("                                                <a href=\"#\" class=\"time pr-2 float-right\">수정</a>\r\n");
      out.write("                                                <!-- <a href=\"#\" class=\"time pr-2 float-right\">답글</a> -->\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <p>Relax my friend</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"comment\">\r\n");
      out.write("                                <ul class=\"comments-list\">\r\n");
      out.write("                                    <li class=\"comment\">\r\n");
      out.write("                                        <a class=\"float-left\" href=\"#\">\r\n");
      out.write("                                            <i class=\"fa fa-reply fa-rotate-180 text-muted\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                            <img class=\"rounded-circle avatar\" src=\"http://bootdey.com/img/Content/user_2.jpg\" alt=\"avatar\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"comment-body\">\r\n");
      out.write("                                            <div class=\"comment-heading\">\r\n");
      out.write("                                                <h4 class=\"user\">Gavino Free</h4>\r\n");
      out.write("                                                <h5 class=\"time\">2020.02.24. 18:22</h5>\r\n");
      out.write("                                                <a href=\"#\" class=\"time pr-2 float-right\">신고</a>\r\n");
      out.write("                                                <!-- <a href=\"#\" class=\"time pr-2 float-right\">답글</a> -->\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <p>Ok, cool.</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                            <!-- 답글 클릭 시 댓글 작성 영역 -->\r\n");
      out.write("                            <li class=\"ml-5\">\r\n");
      out.write("                                <table class=\"replyWrite\">\r\n");
      out.write("                                    <tr>\r\n");
      out.write("                                        <td id=\"replyContentArea\">\r\n");
      out.write("                                            <div class=\"comm_write_wrap\">\r\n");
      out.write("                                                <textArea rows=\"2\" cols=\"50\" class=\"tcol\" id=\"replyContent\" maxlength=\"6000\"></textArea>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                        <td id=\"replyBtnArea\">\r\n");
      out.write("                                            <div class=\"u_cbox_btn_upload\">\r\n");
      out.write("                                                <button class=\"btn\" id=\"addReply\">댓글등록</button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </td>\r\n");
      out.write("                                    </tr>\r\n");
      out.write("                                </table>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                            <li class=\"comment\">\r\n");
      out.write("                                <a class=\"float-left\" href=\"#\">\r\n");
      out.write("                                    <img class=\"rounded-circle avatar\" src=\"http://bootdey.com/img/Content/user_1.jpg\" alt=\"avatar\">\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <div class=\"comment-body\">\r\n");
      out.write("                                    <div class=\"comment-heading\">\r\n");
      out.write("                                        <h4 class=\"user\">Gavino Free</h4>\r\n");
      out.write("                                        <h5 class=\"time\">2020.02.24. 18:08</h5>\r\n");
      out.write("                                        <a href=\"#\" class=\"time pr-2 float-right\">신고</a>\r\n");
      out.write("                                        <a href=\"#\" class=\"time pr-2 float-right\">답글</a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <p>Sure, oooooooooooooooohhhhhhhhhhhhhhhh</p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"comment\">\r\n");
      out.write("                                <ul class=\"comments-list\">\r\n");
      out.write("                                    <li class=\"comment\">\r\n");
      out.write("                                        <a class=\"float-left\" href=\"#\">\r\n");
      out.write("                                            <i class=\"fa fa-reply fa-rotate-180 text-muted\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                            <img class=\"rounded-circle avatar\" src=\"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSIsw4ein7zmQ0GWZq60NBLKwzJ3MkhtkTzEooVnO2jkWGHHcHx\" alt=\"avatar\">\r\n");
      out.write("                                        </a>\r\n");
      out.write("                                        <div class=\"comment-body\">\r\n");
      out.write("                                            <div class=\"comment-heading\">\r\n");
      out.write("                                                <h5 class=\"time\">2020.02.24. 18:08</h5>\r\n");
      out.write("                                                <!-- <a href=\"#\" class=\"time float-right\">신고</a> -->\r\n");
      out.write("                                                <!-- <a href=\"#\" class=\"time pr-2 float-right\">답글</a> -->\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <p>비밀 댓글 입니다</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li> \r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("      \r\n");
      out.write("                      <!-- 댓글 작성 영역 -->\r\n");
      out.write("                      <div>\r\n");
      out.write("                          <table class=\"replyWrite\">\r\n");
      out.write("                              <tr>\r\n");
      out.write("                                  <td id=\"replyContentArea\">\r\n");
      out.write("                                      <div class=\"comm_write_wrap\">\r\n");
      out.write("                                          <textArea rows=\"2\" cols=\"50\" class=\"tcol\" id=\"replyContent\" maxlength=\"6000\"></textArea>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                  </td>\r\n");
      out.write("                                  <td id=\"replyBtnArea\">\r\n");
      out.write("                                        <div class=\"u_cbox_btn_upload\">\r\n");
      out.write("                                            <button class=\"btn\" id=\"addReply\">댓글등록</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                  </td>\r\n");
      out.write("                              </tr>\r\n");
      out.write("                          </table>\r\n");
      out.write("                      </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <hr>\r\n");
      out.write("            <div class=\"col-md-12 text-center\">\r\n");
      out.write("                <button class=\"btn btn-sm btn-outline-secondary float-right\" type=\"button\">목록</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /communityDetail.jsp(23,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(false);
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
